# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Appraisal_Genie.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(799, 611)
        MainWindow.setStyleSheet("background-color: rgb(255, 224, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.app_name = QtWidgets.QLabel(self.centralwidget)
        self.app_name.setGeometry(QtCore.QRect(270, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.app_name.setFont(font)
        self.app_name.setObjectName("app_name")
        self.use_profile = QtWidgets.QPushButton(self.centralwidget)
        self.use_profile.setGeometry(QtCore.QRect(40, 170, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.use_profile.setFont(font)
        self.use_profile.setStyleSheet("\n"
"background-color: rgb(255, 253, 190);")
        self.use_profile.setObjectName("use_profile")
        self.new_profile = QtWidgets.QPushButton(self.centralwidget)
        self.new_profile.setEnabled(True)
        self.new_profile.setGeometry(QtCore.QRect(510, 170, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.new_profile.setFont(font)
        self.new_profile.setStyleSheet("background-color: rgb(252, 255, 234);\n"
"background-color: rgb(254, 255, 190);")
        self.new_profile.setObjectName("new_profile")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(530, 330, 240, 240))
        self.image.setObjectName("image")
        self.help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.help_btn.setEnabled(True)
        self.help_btn.setGeometry(QtCore.QRect(20, 20, 52, 52))
        self.help_btn.setStyleSheet(" border-style: solid;\n"
"background-color: rgb(230, 190, 255);\n"
" border-width:1px;\n"
" border-radius:25px;\n"
" border-color: rgb(239, 156, 255);\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:10px;\n"
" min-height:10px;\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(240, 255, 233);\n"
"background-color: rgb(221, 215, 255);\n"
"color: rgb(255, 241, 83);\n"
"color: rgb(255, 145, 123);\n"
"background-color: rgb(255, 211, 252);")
        self.help_btn.setObjectName("help_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Appraisal Genie"))
        self.app_name.setText(_translate("MainWindow", "Appraisal Genie"))
        self.use_profile.setText(_translate("MainWindow", "Использовать профиль"))
        self.new_profile.setText(_translate("MainWindow", "Создать новый профиль"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.help_btn.setText(_translate("MainWindow", "i"))
