# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Appraisal_Genie_new_profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_profile_window(object):
    def setupUi(self, New_profile_window):
        New_profile_window.setObjectName("New_profile_window")
        New_profile_window.resize(549, 604)
        New_profile_window.setStyleSheet("background-color: rgb(255, 253, 231);\n"
"color: rgb(149, 0, 255);")
        self.profile_name_lineEdit = QtWidgets.QLineEdit(New_profile_window)
        self.profile_name_lineEdit.setGeometry(QtCore.QRect(230, 30, 141, 31))
        self.profile_name_lineEdit.setObjectName("profile_name_lineEdit")
        self.formLayoutWidget = QtWidgets.QWidget(New_profile_window)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 140, 211, 186))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_russian = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_russian.setObjectName("label_russian")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_russian)
        self.lineEdit_russian = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_russian.setObjectName("lineEdit_russian")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_russian)
        self.label_english = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_english.setObjectName("label_english")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_english)
        self.label_math = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_math.setFont(font)
        self.label_math.setObjectName("label_math")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_math)
        self.lineEdit_math = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_math.setObjectName("lineEdit_math")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_math)
        self.label_geometry = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_geometry.setObjectName("label_geometry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_geometry)
        self.lineEdit_geometry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_geometry.setObjectName("lineEdit_geometry")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_geometry)
        self.Label_phys = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_phys.setObjectName("Label_phys")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_phys)
        self.LineEdit_phys = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_phys.setObjectName("LineEdit_phys")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LineEdit_phys)
        self.Label_chem = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_chem.setObjectName("Label_chem")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_chem)
        self.LineEdit_chem = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_chem.setObjectName("LineEdit_chem")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LineEdit_chem)
        self.lineEdit_english = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_english.setObjectName("lineEdit_english")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_english)
        self.label_arith = QtWidgets.QLabel(New_profile_window)
        self.label_arith.setGeometry(QtCore.QRect(30, 330, 161, 51))
        self.label_arith.setObjectName("label_arith")
        self.desire_marks = QtWidgets.QLabel(New_profile_window)
        self.desire_marks.setGeometry(QtCore.QRect(30, 410, 151, 41))
        self.desire_marks.setObjectName("desire_marks")
        self.expect_mark = QtWidgets.QSpinBox(New_profile_window)
        self.expect_mark.setGeometry(QtCore.QRect(250, 420, 42, 22))
        self.expect_mark.setMinimum(2)
        self.expect_mark.setMaximum(5)
        self.expect_mark.setProperty("value", 5)
        self.expect_mark.setObjectName("expect_mark")
        self.arith_mean = QtWidgets.QDoubleSpinBox(New_profile_window)
        self.arith_mean.setGeometry(QtCore.QRect(250, 330, 62, 22))
        self.arith_mean.setSuffix("")
        self.arith_mean.setDecimals(2)
        self.arith_mean.setMinimum(4.5)
        self.arith_mean.setMaximum(5.0)
        self.arith_mean.setSingleStep(0.05)
        self.arith_mean.setProperty("value", 4.5)
        self.arith_mean.setObjectName("arith_mean")
        self.save_btn = QtWidgets.QPushButton(New_profile_window)
        self.save_btn.setGeometry(QtCore.QRect(200, 470, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("background-color: rgb(255, 175, 199);\n"
"color: rgb(255, 243, 172);")
        self.save_btn.setObjectName("save_btn")
        self.label_profile_name = QtWidgets.QLabel(New_profile_window)
        self.label_profile_name.setGeometry(QtCore.QRect(110, 30, 101, 31))
        self.label_profile_name.setObjectName("label_profile_name")
        self.help_btn = QtWidgets.QPushButton(New_profile_window)
        self.help_btn.setEnabled(True)
        self.help_btn.setGeometry(QtCore.QRect(480, 10, 52, 52))
        self.help_btn.setStyleSheet("background-color: rgb(255, 251, 130);\n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:25px;\n"
" border-color: red;\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:10px;\n"
" min-height:10px;\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.help_btn.setObjectName("help_btn")
        self.add_btn = QtWidgets.QPushButton(New_profile_window)
        self.add_btn.setEnabled(True)
        self.add_btn.setGeometry(QtCore.QRect(310, 180, 51, 52))
        self.add_btn.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(211, 245, 255);\n"
"color: rgb(255, 135, 124);\n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:13px;\n"
" border-color: red;\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:10px;\n"
" min-height:10px;")
        self.add_btn.setObjectName("add_btn")
        self.extra_subjects = QtWidgets.QWidget(New_profile_window)
        self.extra_subjects.setGeometry(QtCore.QRect(240, 100, 301, 201))
        self.extra_subjects.setObjectName("extra_subjects")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.extra_subjects)
        self.formLayoutWidget_2.setEnabled(True)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 281, 161))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.extra_sub_1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_1.setEnabled(True)
        self.extra_sub_1.setObjectName("extra_sub_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.extra_sub_1)
        self.extra_sub_marks_1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_1.setEnabled(True)
        self.extra_sub_marks_1.setObjectName("extra_sub_marks_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_1)
        self.extra_sub_marks_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_2.setEnabled(True)
        self.extra_sub_marks_2.setObjectName("extra_sub_marks_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_2)
        self.extra_sub_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_3.setEnabled(True)
        self.extra_sub_3.setObjectName("extra_sub_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.extra_sub_3)
        self.extra_sub_marks_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_3.setEnabled(True)
        self.extra_sub_marks_3.setObjectName("extra_sub_marks_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_3)
        self.extra_sub_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_4.setEnabled(True)
        self.extra_sub_4.setObjectName("extra_sub_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.extra_sub_4)
        self.extra_sub_marks_4 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_4.setEnabled(True)
        self.extra_sub_marks_4.setObjectName("extra_sub_marks_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_4)
        self.extra_sub_5 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_5.setEnabled(True)
        self.extra_sub_5.setObjectName("extra_sub_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.extra_sub_5)
        self.extra_sub_marks_5 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_5.setEnabled(True)
        self.extra_sub_marks_5.setObjectName("extra_sub_marks_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_5)
        self.extra_sub_6 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_6.setEnabled(True)
        self.extra_sub_6.setObjectName("extra_sub_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.extra_sub_6)
        self.extra_sub_marks_6 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_marks_6.setEnabled(True)
        self.extra_sub_marks_6.setObjectName("extra_sub_marks_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.extra_sub_marks_6)
        self.extra_sub_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.extra_sub_2.setEnabled(True)
        self.extra_sub_2.setObjectName("extra_sub_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.extra_sub_2)
        self.label_extra_subject = QtWidgets.QLabel(self.extra_subjects)
        self.label_extra_subject.setGeometry(QtCore.QRect(30, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_extra_subject.setFont(font)
        self.label_extra_subject.setObjectName("label_extra_subject")
        self.label_extra_mark = QtWidgets.QLabel(self.extra_subjects)
        self.label_extra_mark.setGeometry(QtCore.QRect(170, 10, 61, 16))
        self.label_extra_mark.setObjectName("label_extra_mark")
        self.error = QtWidgets.QLabel(New_profile_window)
        self.error.setGeometry(QtCore.QRect(10, 70, 601, 41))
        self.error.setStyleSheet("color: rgb(255, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_subject = QtWidgets.QLabel(New_profile_window)
        self.label_subject.setGeometry(QtCore.QRect(20, 110, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_subject.setFont(font)
        self.label_subject.setObjectName("label_subject")
        self.label_mark = QtWidgets.QLabel(New_profile_window)
        self.label_mark.setGeometry(QtCore.QRect(120, 110, 61, 16))
        self.label_mark.setObjectName("label_mark")
        self.back_btn = QtWidgets.QPushButton(New_profile_window)
        self.back_btn.setGeometry(QtCore.QRect(10, 10, 52, 52))
        self.back_btn.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"font: 72pt \"MS Shell Dlg 2\";\n"
"font: 48pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(230, 236, 255);\n"
"\n"
"\n"
"\n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:13px;\n"
" border-color: red;\n"
" max-width:50px;\n"
" max-height:50px;\n"
" min-width:10px;\n"
" min-height:10px;")
        self.back_btn.setObjectName("back_btn")
        self.image = QtWidgets.QLabel(New_profile_window)
        self.image.setGeometry(QtCore.QRect(390, 320, 131, 161))
        self.image.setObjectName("image")
        self.profile_name_lineEdit.raise_()
        self.formLayoutWidget.raise_()
        self.label_arith.raise_()
        self.desire_marks.raise_()
        self.expect_mark.raise_()
        self.arith_mean.raise_()
        self.save_btn.raise_()
        self.label_profile_name.raise_()
        self.help_btn.raise_()
        self.extra_subjects.raise_()
        self.add_btn.raise_()
        self.error.raise_()
        self.label_subject.raise_()
        self.label_mark.raise_()
        self.back_btn.raise_()
        self.image.raise_()

        self.retranslateUi(New_profile_window)
        QtCore.QMetaObject.connectSlotsByName(New_profile_window)

    def retranslateUi(self, New_profile_window):
        _translate = QtCore.QCoreApplication.translate
        New_profile_window.setWindowTitle(_translate("New_profile_window", "Appraisal Genie создание профиля"))
        self.profile_name_lineEdit.setText(_translate("New_profile_window", "Введите имя профиля"))
        self.label_russian.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Русский яз.</span></p></body></html>"))
        self.label_english.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Англйиский</span></p></body></html>"))
        self.label_math.setText(_translate("New_profile_window", "Алгебра"))
        self.label_geometry.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Геометрия</span></p></body></html>"))
        self.Label_phys.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Физика</span></p></body></html>"))
        self.Label_chem.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Химия </span></p></body></html>"))
        self.label_arith.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">C какого среднего балла</span></p><p><span style=\" font-size:10pt;\">начинается 5?</span></p></body></html>"))
        self.desire_marks.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Какую оценку желаете?</span></p></body></html>"))
        self.save_btn.setText(_translate("New_profile_window", "Сохранить"))
        self.label_profile_name.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:10pt;\">Имя профиля</span></p></body></html>"))
        self.help_btn.setText(_translate("New_profile_window", "?"))
        self.add_btn.setText(_translate("New_profile_window", "+"))
        self.label_extra_subject.setText(_translate("New_profile_window", "Предметы"))
        self.label_extra_mark.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:9pt;\">Оценки</span></p></body></html>"))
        self.label_subject.setText(_translate("New_profile_window", "Предметы"))
        self.label_mark.setText(_translate("New_profile_window", "<html><head/><body><p><span style=\" font-size:9pt;\">Оценки</span></p></body></html>"))
        self.back_btn.setText(_translate("New_profile_window", "🠔"))
        self.image.setText(_translate("New_profile_window", "TextLabel"))
